project:
  type: website
  output-dir: docs
  render:
    - index.qmd

format:
  html:
    theme: pulse
    embed-resources: true
    toc: true
    toc-location: left
    code-fold: true
    smooth-scroll: true