project:
  type: website
  output-dir: docs
  render:
    - index.qmd

format:
  html:
    theme: pulse
    embed-resources: true
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
  
    grid:
      sidebar-width: 150px     # navigation sidebar
      margin-width: 0px      # TOC width
      body-width: 900px
      gutter-width: 3.5rem

    css: styles.css